---
#Use individual namespace for litecoin
#Namespace represent the logically groups and manages Kubernetes resources
apiVersion: v1
kind: Namespace
metadata:
  name: litecoin  
---
#Use specific service account for litecoin 
#The service accounts inject authentication credentials into the pod to talk to the Kubernetes service
apiVersion: v1
kind: ServiceAccount
metadata:
  name: litecoin
  namespace: litecoin
---
#Statefulset of litecoin services deployment
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: litecoin
  name: litecoin
  labels: &litecoin-labels
    app: litecoin
    component: daemon
    #version of litecoin
    version: '0.18.1' 
spec:
  selector:
    matchLabels: *litecoin-labels
  serviceName: litecoin
  #Number of replicas
  replicas: 1  
  template:
    metadata:
      labels: *litecoin-labels
    spec:
      serviceAccountName: litecoin
      securityContext:
        runAsUser: 1001 
        fsGroup: 1001
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      tolerations:
      - key: preemptible
        operator: Equal
        value: "true"
        effect: NoSchedule
      containers:
        - name: main
          image: kantsuw/litecoin:0.18.1
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: litecoin-data
            mountPath: "/home/litecoin/.litecoin"
          #Resource limit              
          resources:  
            requests:
              memory: 256Mi
            limits:
              cpu: 0.5
              memory: 256Mi
          readinessProbe:
            tcpSocket:
              port: 9333
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 3 
  #volumeClaim of service              
  volumeClaimTemplates: 
    - metadata:
        name: litecoin-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 10Gi
